---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

services:
  - docker

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  # run playbook
  - "ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo"
  # Run the playbook again, checking idempotence.
  - >
    ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
  # pinging host, using bootstrapped python
  - "ansible -i tests/$TEST/inventory all -m ping"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/