---

- include: "docker-{{ ansible_os_family }}.yml"
  when: '"{{ ansible_os_family }}" in container_specific_os_family'

- name: Create Host OS nginx volumes folders
  become: true
  file:
    path: '{{ item }}'
    state: 'directory'
    owner: '{{ host_nginx_user }}'
    group: '{{ host_nginx_group }}'
    mode: '0755'
  with_items:
    - '{{ host_nginx_log }}'
    - '{{ host_nginx_conf }}'
