---
# tasks file for ansible-coreos-nginx

# Variable setup.
- name: Include OS Specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: If system is container specific, include Docker variables
  when: '"{{ ansible_os_family }}" in container_specific_os_family'
  include_vars: nginx_docker.yml

- name: If system is container specific, include Docker variables
  when: '"{{ ansible_os_family }}" in non_container_specific_os_family'
  include_vars: nginx_non_docker.yml

- name: Define nginx_user.
  set_fact:
    nginx_user: "{{ __nginx_user }}"
  when: nginx_user is not defined

# Setup:
#   - write Docker file in host OS
#   - copy SSL certificates in host OS
#   - set volumes for:
#     - error log
#     - access log
- include: "setup-{{ ansible_os_family }}.yml"

- name: Copy nginx configuration in place.
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf_file_path }}"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  register: nginx_configured

- name: Docker container
  docker:
    name: my_nginx
    image: '{{ nginx_host_docker_image_id }}'
    state: started
    ports: 80:80
    restart_policy: always
    log_driver: 'syslog'
    log_opt:
      syslog-tag: "{{ nginx_container_name }}"
    # state: present
    # recreate: yes
    # exposed_ports:
    #   - 6379
    # volumes_from:
    #   - mydata

# - name: Copy nginx configuration in place.
#   template:
#     src: nginx.conf.j2
#     dest: "{{ nginx_host_directory }}/nginx.conf"
#     owner: "{{ nginx_user }}"
#     group: "{{ root_group }}"
#     mode: 0644

#   notify:
#     - restart-docker-nginx

# - name: 'start-docker-nginx'
#   become: yes
#   docker:
#     image: "nginx:{{ nginx_docker_tag }}"
#     name: "{{ nginx_container_name }}"
#     restart_policy: 'always'
#     log_driver: 'syslog'
#     log_opt:
#       syslog-tag: "{{ nginx_container_name }}"

# - name: launch nginx container
#   docker:
#     image: "nginx:{{ nginx_docker_tag }}"
#     name: "example-nginx"
#     ports: "80:80"
#     state: started
#     restart_policy: 'always'
#     log_driver: 'syslog'
#     log_opt:
#       syslog-tag: "{{ nginx_container_name }}"
