---
# tasks file for ansible-coreos-nginx

- name: Include OS Specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: If system is container specific, include Docker variables
  when: '"{{ ansible_os_family }}" in container_specific_os_family'
  include_vars: nginx_docker.yml

- name: If system is container specific, include Docker variables
  when: '"{{ ansible_os_family }}" in non_container_specific_os_family'
  include_vars: nginx_non_docker.yml

- name: Define nginx_user.
  set_fact:
    nginx_user: "{{ __nginx_user }}"
  when: nginx_user is not defined

- include: "setup-{{ ansible_os_family }}.yml"

- include: ssl_config.yml
  when: ssl_key_fname is defined and
        ssl_cert_fname is defined

- include: 'vhost.yml'

- name: Copy nginx configuration in place.
  template:
    src: nginx.conf.j2
    dest: '{{ nginx_conf_file_path }}'
    owner: '{{ user_host_directory }}'
    group: '{{ group_host_directory }}'
    mode: 0644
  register: nginx_configured

- name: remove docker container
  docker:
    name: my_nginx
    image: '{{ nginx_docker_image_name }}/{{ nginx_docker_image_tag }}'
    state: '{{ item }}'
  with_items:
    - stopped
    - killed
    - absent

- name: launch nginx container
  docker:
    image: '{{ nginx_docker_image_name }}:{{ nginx_docker_image_tag }}'
    name: "jupyterhub-nginx"
    ports: '{{ nginx_published_ports }}'
    expose: '{{ nginx_exposed_ports }}'
    volumes: '{{ nginx_exposed_volumes }}' 
    state: started
    restart_policy: 'always'
    log_driver: 'syslog'
    log_opt:
      syslog-tag: "{{ nginx_container_name }}"
