---
# tasks file for ansible-coreos-nginx

- name: Include OS Specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: If system is container specific, include Docker variables
  when: '"{{ ansible_os_family }}" in container_specific_os_family'
  include_vars: nginx_docker.yml

- include: configure_HostOS.yml

################################################################################
#                       
#                             GENERATE COFNIG FILES

- include: ssl_config.yml
  when: ssl_key_fname is defined and
        ssl_cert_fname is defined

- include: 'vhost.yml'

- name: Copy nginx configuration in place.
  template:
    src: nginx.conf.j2
    dest: '{{ nginx_conf_file_path }}'
    owner: '{{ user_host_directory }}'
    group: '{{ group_host_directory }}'
    mode: 0644
  register: nginx_configured

- name: Copy default web page to Host OS
  copy:
    src: '{{ host_static_html_directory }}'
    dest: '{{ nginx_host_config }}'
    mode: '0644'

- name: Copy docker template
  template:
    src: Dockerfile.j2
    dest: '{{ nginx_host_config }}/Dockerfile'
    mode: 0644
  register: dockerfile_status

################################################################################
#                       
#                             Docker

- name: Build Dockerfile image
  when: dockerfile_status | changed
  docker_image:
    path: '{{ nginx_host_config }}'
    name: '{{ nginx_docker_image_name }}'
    tag: '{{ nginx_docker_image_tag }}'
    state: present
  register: image_output

- name: Save docker image ID
  when: dockerfile_status | changed
  set_fact:
    nginx_host_docker_image_id: '{{ image_output.image_id }}'

- name: remove docker container
  docker:
    name: my_nginx
    image: '{{ nginx_docker_image_name }}/{{ nginx_docker_image_tag }}'
    state: '{{ item }}'
  with_items:
    - stopped
    - killed
    - absent

- name: launch nginx container
  docker:
    image: '{{ nginx_docker_image_name }}:{{ nginx_docker_image_tag }}'
    name: "jupyterhub-nginx"
    ports: '{{ nginx_published_ports }}'
    expose: '{{ nginx_exposed_ports }}'
    volumes: '{{ nginx_exposed_volumes }}' 
    state: started
    restart_policy: 'always'
    log_driver: 'syslog'
    log_opt:
      syslog-tag: "{{ nginx_container_name }}"
