---

- include: "docker-{{ ansible_os_family }}.yml"

- name: Create Host OS nginx volumes folders
  file:
    path: '{{ item }}'
    state: 'directory'
    mode: '0755'
  with_items:
    - '{{ nginx_host_log }}'
    - '{{ nginx_host_docker_ids }}'
    - '{{ nginx_work_dir }}'

- name: Copy default web page to Host OS
  copy:
    src: '{{ host_static_html_directory }}'
    dest: '{{ nginx_host_config }}'
    mode: '0644'

- name: Copy docker template
  template:
    src: Dockerfile.j2
    dest: '{{ nginx_host_config }}/Dockerfile'
    mode: 0644

- name: Build Dockerfile image
  docker_image:
    path: '{{ nginx_host_config }}'
    name: '{{ nginx_docker_image_name }}'
    tag: '{{ nginx_docker_image_tag }}'
    state: present
  register: image_output

- name: Save docker image ID
  set_fact:
    nginx_host_docker_image_id: '{{ image_output.image_id }}'

# Move files to the host OS.
# - Copy SSL certificates
# - Copy virtual servers
# - Copy configuration

# - name: pull container
#   raw: docker pull nginx:1.7.1

# - name: launch nginx container
#   docker:
#     image='nginx:1.7.1'
#     name='example-nginx'
#     ports='8080:80'
#     state=started