---

# CoreOS needs the etcd service running.
- name: Start etcd
  service: name=etcd.service state=started
  become: yes
  become_user: root

- name: Start etcd
  service: name=etcd.service state=started
  become: yes
  become_user: root

- name: Install docker-py
  pip: name=docker-py version=1.2.3

- name: Create Host OS nginx volumes folders
  file:
    path: '{{ item }}'
    state: 'directory'
    mode: '0755'
  with_items:
    - '{{ nginx_host_log }}'
    - '{{ nginx_host_config }}/certs'
    - '{{ nginx_host_config }}/etc_conf'

- name: Copy default web page to Host OS
  copy:
    src: '{{ host_static_html_directory }}'
    dest: '{{ nginx_host_config }}'
    mode: '0644'

- name: pull "{{ nginx_container_name }}:{{ nginx_docker_tag }}" image
  docker_image:
    name: "{{ nginx_container_name }}:{{ nginx_docker_tag }}"

# Move files to the host OS.
# - Copy SSL certificates
# - Copy virtual servers
# - Copy configuration

# - name: pull container
#   raw: docker pull nginx:1.7.1

# - name: launch nginx container
#   docker:
#     image='nginx:1.7.1'
#     name='example-nginx'
#     ports='8080:80'
#     state=started