---

# Write Dockerfile

# Copy SSL certificates

# Copy virtual servers

# Copy configuration

# Run Docker fil
- name: Start etcd
  service: name=etcd.service state=started
  become: yes
  become_user: root

- name: Install docker-py
  pip: name=docker-py version=1.2.3

- name: pull container
  raw: docker pull nginx:1.7.1

- name: launch nginx container
  docker:
    image="nginx:1.7.1"
    name="example-nginx"
    ports="8080:80"
    state=started