---

- name: Define nginx ssl path
  set_fact:
    nginx_ssl_path: '{{ nginx_ssl_default_path }}'
  when: nginx_ssl_path is not defined

- name: Define where nginx is going to look for the ssl keys and certs
  set_fact:
    ssl_cert_path: '{{ nginx_ssl_cert_folder }}/{{ ssl_cert_fname }}'
    ssl_key_path: '{{ nginx_ssl_cert_folder }}/{{ ssl_key_fname }}'
  when: ssl_key_fname is defined and
        ssl_cert_fname is defined

- name: Create Host OS SSL folder
  file:
    path: '{{ nginx_ssl_default_path }}'
    state: 'directory'
    mode: '0755'

- name: Copy SSL certificates to host OS
  template:
    src:   '{{ item.from }}'
    dest:  '{{ item.path }}'
    owner: '{{ user_host_directory }}'
    group: '{{ group_host_directory }}'
    mode:  0640
  with_items:
  - from: ssl.key.j2
    path: '{{ nginx_ssl_path }}/{{ ssl_key_fname }}'
  - from: ssl.crt.j2
    path: '{{ nginx_ssl_path }}/{{ ssl_cert_fname }}'
  register: conf_ssl
  when: ssl_key_fname is defined and
        ssl_cert_fname is defined